name: TESTreservation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup TESTreservation
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Build and push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
       image: miboumi/reservationtest
       registry: docker.io
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}
       
    - name: Deploy Docker image on Heroku
      id: heroku
      uses: jctaveras/heroku-deploy@v2.1.2 # use the latest version of the action
      with:
          email: "omayma.hajjami96@gmail.com" # your heroku email
          api_key: ${{ secrets.HEROKU_API_KEY }} # your heroku api key
          app_name: "reservationtest" # you aplication name
          dockerfile_path: '.' # set the path to the folder where the Dockerfile is located
    
